<script setup lang="ts">
import{onMounted,onUnmounted,ref,watch}from'vue';import{ElMessage,ElMessageBox}from'element-plus';import{api}from'../api';import type{Project,Source}from'../types';import StatusTag from'../components/StatusTag.vue';import{validateSourceFile}from'../utils/files'
const projects=ref<Project[]>([]),projectId=ref(''),sources=ref<Source[]>([]),uploading=ref(false),progress=ref(0),query=ref(''),results=ref<any[]>([]),searching=ref(false);let timer:number|undefined
async function loadSources(){if(!projectId.value)return;sources.value=await api.sources(projectId.value);if(sources.value.some(s=>['uploaded','parsing','indexing'].includes(s.status)))timer=window.setTimeout(loadSources,1800)}
async function choose(file:File){if(!projectId.value){ElMessage.warning('请先选择项目');return}const validation=validateSourceFile(file);if(validation){ElMessage.error(validation);return}uploading.value=true;try{await api.upload(projectId.value,file,v=>progress.value=v);ElMessage.success('上传成功，正在建立索引');await loadSources()}catch(e){ElMessage.error((e as Error).message)}finally{uploading.value=false}}
async function remove(s:Source){await ElMessageBox.confirm(`确定删除“${s.original_name}”及其索引吗？`,'删除资料');await api.deleteSource(projectId.value,s.id);await loadSources()}
async function search(){if(!query.value.trim())return;searching.value=true;try{results.value=await api.search(projectId.value,query.value);if(!results.value.length)ElMessage.info('没有找到相关证据，请换一种问法')}catch(e){ElMessage.error((e as Error).message)}finally{searching.value=false}}
watch(projectId,()=>{clearTimeout(timer);loadSources()});onMounted(async()=>{projects.value=await api.projects();projectId.value=projects.value[0]?.id||''});onUnmounted(()=>clearTimeout(timer))
</script>
<template><section><div class="page-head"><div><h2>资料知识库</h2><p>上传教材、课标或教案；每条检索结果都保留文件与原文位置。</p></div><el-select v-model="projectId" placeholder="选择备课项目" style="width:270px"><el-option v-for="p in projects" :key="p.id" :label="p.name" :value="p.id"/></el-select></div><el-empty v-if="!projects.length" description="请先创建备课项目"/><div v-else class="kb-grid"><div class="panel panel-pad"><label class="upload-zone"><input hidden type="file" accept=".pdf,.docx,.txt,.md" @change="choose(($event.target as HTMLInputElement).files![0])"/><h3>拖放或点击上传资料</h3><p class="muted">支持 PDF / DOCX / TXT / Markdown，单文件不超过 20MB</p><el-progress v-if="uploading" :percentage="progress"/></label><h3>已上传资料</h3><div v-if="!sources.length" class="muted">暂无资料</div><div v-for="s in sources" :key="s.id" class="file-row"><div class="file-info"><b>{{s.original_name}}</b><span class="meta">{{(s.size/1024).toFixed(1)}} KB · {{s.error_message||'来源将按页码/段落追溯'}}</span></div><StatusTag :status="s.status"/><el-button v-if="s.status==='failed'" link @click="api.retrySource(projectId,s.id).then(loadSources)">重试</el-button><el-button link type="danger" @click="remove(s)">删除</el-button></div></div><div class="panel panel-pad"><h3>检索测试</h3><p class="muted">验证 AI 是否能找到与问题相关的真实资料片段。</p><el-input v-model="query" type="textarea" :rows="3" placeholder="例如：本课对应的课程标准要求是什么？"/><el-button type="primary" style="width:100%;margin-top:10px" :loading="searching" @click="search">检索证据</el-button><div v-for="r in results" :key="r.chunk_id" class="search-result"><b>{{r.filename}}</b><el-tag size="small" style="float:right">相关度 {{r.score}}</el-tag><p>{{r.content}}</p><span class="meta">{{r.location}} · {{r.chunk_id}}</span></div></div></div></section></template>
