<script setup lang="ts">
import {onMounted,reactive,ref} from 'vue';import {useRouter} from 'vue-router';import {ElMessage} from 'element-plus';import {api,type ProjectInput} from '../api';import type{Project}from'../types';import AppState from '../components/AppState.vue'
const router=useRouter(),projects=ref<Project[]>([]),loading=ref(true),error=ref(''),dialog=ref(false),saving=ref(false)
const form=reactive<ProjectInput>({name:'',subject:'语文',grade:'小学三年级',textbook_version:'',lesson_topic:'',lesson_count:1,student_profile:'',teacher_requirements:''})
async function load(){loading.value=true;error.value='';try{projects.value=await api.projects()}catch(e){error.value=(e as Error).message}finally{loading.value=false}}
async function create(){if(!form.name.trim()||!form.lesson_topic.trim()){ElMessage.warning('请填写项目名称和课题');return}saving.value=true;try{const p=await api.createProject(form);dialog.value=false;router.push(`/workbench/${p.id}`)}catch(e){ElMessage.error((e as Error).message)}finally{saving.value=false}}
onMounted(load)
</script>
<template><section><div class="page-head"><div><h2>备课项目</h2><p>从课程信息开始，AI 会把资料、设计、课件与评价组织成同一条教学链。</p></div><el-button type="primary" size="large" @click="dialog=true">＋ 开始备课</el-button></div>
<AppState :loading="loading" :error="error" :empty="!projects.length" empty-text="还没有备课项目，创建第一个课例吧" @retry="load"><div class="project-grid"><article v-for="p in projects" :key="p.id" class="panel project-card" @click="router.push(`/workbench/${p.id}`)"><el-tag effect="plain">{{p.grade}} · {{p.subject}}</el-tag><h3>{{p.name}}</h3><p>{{p.lesson_topic}}</p><div class="meta">{{p.textbook_version||'未指定教材版本'}} · {{p.lesson_count}} 课时</div></article></div></AppState>
<el-dialog v-model="dialog" title="创建单课时备课项目" width="680"><el-form label-position="top"><div class="row"><el-form-item class="grow" label="项目名称" required><el-input v-model="form.name" placeholder="例如：三年级语文公开课"/></el-form-item><el-form-item class="grow" label="课题" required><el-input v-model="form.lesson_topic" placeholder="请输入本课课题"/></el-form-item></div><div class="row"><el-form-item class="grow" label="学科"><el-select v-model="form.subject" style="width:100%"><el-option v-for="x in ['语文','数学','英语','科学','道德与法治']" :key="x" :value="x"/></el-select></el-form-item><el-form-item class="grow" label="年级"><el-input v-model="form.grade"/></el-form-item><el-form-item class="grow" label="课时"><el-input-number v-model="form.lesson_count" :min="1" :max="8"/></el-form-item></div><el-form-item label="教材版本"><el-input v-model="form.textbook_version" placeholder="例如：人教版三年级上册"/></el-form-item><el-form-item label="学情特点（可选）"><el-input v-model="form.student_profile" type="textarea"/></el-form-item><el-form-item label="教师补充要求（可选）"><el-input v-model="form.teacher_requirements" type="textarea"/></el-form-item></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" :loading="saving" @click="create">创建并进入工作台</el-button></template></el-dialog></section></template>

