<script setup lang="ts">
import{onMounted,ref}from'vue';import{useRoute,useRouter}from'vue-router';import{ElMessage}from'element-plus';import{api}from'../api';import type{GraphState}from'../types'
const route=useRoute(),router=useRouter(),pid=String(route.params.projectId),graph=ref<GraphState>({status:'not_started',nodes:[],issues:[]})
const labels:Record<string,string>={analyze_sources:'资料分析',design_lesson:'教学设计',generate_slides:'课件生成',generate_notes_exercises:'讲稿/练习',review_quality:'质量审校',human_confirm:'人工确认',finalize:'完成'}
async function load(){graph.value=await api.graph(pid)}
async function decide(decision:string){if(!graph.value.id)return;await api.confirmGraph(graph.value.id,decision);ElMessage.success('已提交教师决定');await load()}
onMounted(load)
</script>
<template><section><div class="page-head"><div><h2>多智能体质量流程</h2><p>生成、审校、定向返修与人工确认都保持可见。</p></div><el-button @click="router.push(`/workbench/${pid}`)">返回工作台</el-button></div><div class="panel panel-pad"><h3>流程状态</h3><div v-if="graph.nodes.length" class="node-flow"><template v-for="(n,i) in graph.nodes" :key="n.node_id"><span :class="['node',n.status]">{{labels[n.node_id]||n.node_id}}</span><span v-if="i<graph.nodes.length-1">→</span></template></div><el-empty v-else description="尚未运行完整生成任务"/><el-divider/><h3>审校问题</h3><p v-if="!graph.issues.length" class="muted">确定性规则未发现阻断问题，仍需教师最终确认。</p><div v-for="i in graph.issues" :key="i.target_id+i.issue_type" :class="['issue',i.severity]"><b>{{i.target_id}} · {{i.issue_type}}</b><p>{{i.suggestion}}</p></div><template v-if="graph.status==='awaiting_confirmation'||graph.status==='needs_revision'"><el-divider/><h3>教师最终确认</h3><p>AI 只提供备课草案，确认权始终属于教师。</p><el-button @click="decide('revise')">返回修改</el-button><el-button type="primary" @click="decide('accept')">确认并允许导出</el-button></template><el-result v-if="graph.status==='succeeded'" icon="success" title="教师已确认" sub-title="现在可以导出教师包或学生包"><template #extra><el-button type="primary" @click="router.push(`/export/${pid}`)">前往导出</el-button></template></el-result></div></section></template>
