<script setup lang="ts">
import{computed,onMounted,onUnmounted,ref}from'vue';import{useRoute,useRouter}from'vue-router';import{ElMessage}from'element-plus';import{api}from'../api';import type{Artifact,Citation,Project,Task}from'../types';import StatusTag from'../components/StatusTag.vue'
const route=useRoute(),router=useRouter(),pid=String(route.params.projectId),project=ref<Project>(),skills=ref<any[]>([]),tasks=ref<Task[]>([]),artifacts=ref<Artifact[]>([]),activeType=ref('lesson_plan'),selectedSlide=ref('SLIDE-01'),selectedCitation=ref<Citation>(),drawerVisible=ref(false),exerciseView=ref('教师视图'),running=ref(false),revision=ref(''),sync=ref(true);let timer:number|undefined
const artifact=computed(()=>artifacts.value.find(a=>a.type===activeType.value));const deck=computed(()=>artifacts.value.find(a=>a.type==='slide_deck'));const notes=computed(()=>artifacts.value.find(a=>a.type==='speaker_notes'));const selected=computed(()=>deck.value?.content.slides?.find((s:any)=>s.slide_id===selectedSlide.value));const selectedNote=computed(()=>notes.value?.content.notes?.find((n:any)=>n.slide_id===selectedSlide.value));
async function load(){try{[project.value,skills.value,tasks.value,artifacts.value]=await Promise.all([api.project(pid),api.skills(),api.tasks(pid),api.artifacts(pid)]);const busy=tasks.value.find(t=>['pending','running'].includes(t.status));if(busy)timer=window.setTimeout(load,1500);else running.value=false}catch(e){ElMessage.error((e as Error).message)}}
async function generate(type='full_lesson'){running.value=true;try{await api.createTask(pid,{type,selected_source_ids:[],teacher_requirements:project.value?.teacher_requirements||'',idempotency_key:`${type}-${Date.now()}`});await load()}catch(e){running.value=false;ElMessage.error((e as Error).message)}}
async function revise(){if(!artifact.value||!revision.value.trim())return;const targetType=activeType.value==='slide_deck'?'slide':activeType.value==='speaker_notes'?'note':activeType.value==='exercise_set'?'exercise':'stages';const targetId=activeType.value==='lesson_plan'?(artifact.value.content.stages?.[0]?.id||''):selectedSlide.value;try{const changed=await api.revise(artifact.value.artifact_id,{base_version_no:artifact.value.version_no,target_type:targetType,target_id:targetId,instruction:revision.value,sync_related:sync.value});artifacts.value=artifacts.value.map(a=>a.artifact_id===changed.artifact_id?changed:a);revision.value='';ElMessage.success(`已创建 v${changed.version_no}，仅更新目标内容`);await load()}catch(e){ElMessage.error((e as Error).message);await load()}}
function cite(c:Citation){selectedCitation.value=c;drawerVisible.value=true}
onMounted(load);onUnmounted(()=>clearTimeout(timer))
</script>
<template><section v-if="project"><div class="page-head"><div><h2>{{project.lesson_topic}}</h2><p>{{project.grade}} · {{project.subject}} · {{project.textbook_version||'未指定教材版本'}}</p></div><div><el-button @click="router.push(`/quality/${pid}`)">质量检查</el-button><el-button type="primary" :loading="running" @click="generate()">{{artifacts.length?'重新生成':'生成完整备课包'}}</el-button></div></div><div class="workbench"><aside class="panel work-col context-box"><p class="eyebrow">课程输入</p><h3>{{project.name}}</h3><p class="muted">{{project.student_profile||'尚未填写学情特点'}}</p><el-divider/><p class="eyebrow">五类教学 Skills</p><div v-for="s in skills" :key="s.id" class="skill-card"><b>{{s.name}}</b><p class="meta">{{s.description}}</p><el-button link type="primary" :disabled="running" @click="generate(s.id)">运行此 Skill →</el-button></div><el-divider/><p class="eyebrow">最近任务</p><div v-for="t in tasks.slice(0,3)" :key="t.id" style="margin:10px 0"><StatusTag :status="t.status"/> <span class="meta">{{t.stage}} · {{t.progress}}%</span><el-progress v-if="t.status==='running'" :percentage="t.progress" :show-text="false"/></div></aside>
<main class="panel work-col artifact-area"><el-tabs v-model="activeType"><el-tab-pane label="教学设计" name="lesson_plan"/><el-tab-pane label="课件" name="slide_deck"/><el-tab-pane label="讲稿" name="speaker_notes"/><el-tab-pane label="练习" name="exercise_set"/></el-tabs><el-empty v-if="!artifact" description="选择左侧 Skill 或生成完整备课包后，产物会出现在这里"/>
<template v-else><div v-for="w in artifact.warnings" :key="w" class="warning">{{w}}</div><template v-if="activeType==='lesson_plan'"><h2>{{artifact.content.title}}</h2><h3>教学目标</h3><div v-for="o in artifact.content.objectives" :key="o.id" class="notes-card"><el-tag>{{o.id}}</el-tag> {{o.behavior}}<p class="meta">条件：{{o.condition}} · 标准：{{o.criterion}}</p></div><h3>课堂流程</h3><el-timeline><el-timeline-item v-for="s in artifact.content.stages" :key="s.id" :timestamp="`${s.time_minutes} 分钟`"><b>{{s.name}}</b><p>教师：{{s.teacher_actions}}</p><p>学生：{{s.student_actions}}</p></el-timeline-item></el-timeline></template>
<template v-if="activeType==='slide_deck'"><div class="row"><div class="slide-list"><div v-for="s in artifact.content.slides" :key="s.slide_id" :class="['slide-thumb',{active:selectedSlide===s.slide_id}]" @click="selectedSlide=s.slide_id"><b>{{s.order}}. {{s.title}}</b><br>{{s.teaching_stage}}</div></div><div class="grow"><div class="slide-stage"><h1>{{selected?.title}}</h1><p>{{selected?.markdown}}</p></div><div v-if="selectedNote" class="notes-card"><b>同步讲稿</b><p>{{selectedNote.explanation}}</p><span class="meta">{{selectedNote.transition}}</span></div></div></div></template>
<template v-if="activeType==='speaker_notes'"><div v-for="n in artifact.content.notes" :key="n.slide_id" class="notes-card" @click="selectedSlide=n.slide_id"><el-tag>{{n.slide_id}}</el-tag><p>{{n.explanation}}</p><b>课堂提问</b><ul><li v-for="q in n.questions" :key="q">{{q}}</li></ul><span class="meta">过渡：{{n.transition}} · 板书：{{n.board_notes}}</span></div></template>
<template v-if="activeType==='exercise_set'"><el-segmented v-model="exerciseView" :options="['教师视图','学生预览']"/><div v-for="e in artifact.content.exercises" :key="e.exercise_id" class="notes-card" @click="selectedSlide=e.exercise_id"><el-tag>{{e.level}}</el-tag> <b>{{e.question}}</b><template v-if="exerciseView==='教师视图'"><p>答案：{{e.answer}}</p><p class="meta">解析：{{e.explanation}}</p></template><el-tag v-if="e.needs_teacher_review&&exerciseView==='教师视图'" type="warning">需教师确认</el-tag></div></template>
<el-divider/><h3>局部修改当前内容</h3><el-input v-model="revision" type="textarea" placeholder="例如：把当前页改成更适合三年级学生的提问式表达"/><el-checkbox v-model="sync">同步关联讲稿/练习（仅限同一 ID）</el-checkbox><el-button type="primary" plain @click="revise">保存为新版本</el-button></template></main>
<aside class="panel work-col context-box"><el-tabs><el-tab-pane label="来源"><p class="muted">点击来源可核对原文，AI 建议与资料事实分开标识。</p><span v-for="c in artifact?.citations||[]" :key="c.chunk_id" class="citation" @click="cite(c)"><b>{{c.filename}}</b><small>{{c.location}}</small></span><el-empty v-if="!artifact?.citations.length" :image-size="60" description="暂无可追溯来源"/></el-tab-pane><el-tab-pane label="版本"><div v-if="artifact"><h3>当前 v{{artifact.version_no}}</h3><p class="meta">每次生成、局部修改和回滚都会创建不可变版本。</p></div></el-tab-pane></el-tabs></aside></div><el-drawer v-model="drawerVisible" title="资料原文" size="420px"><template v-if="selectedCitation"><el-descriptions :column="1" border><el-descriptions-item label="文件">{{selectedCitation.filename}}</el-descriptions-item><el-descriptions-item label="位置">{{selectedCitation.location}}</el-descriptions-item><el-descriptions-item label="分块">{{selectedCitation.chunk_id}}</el-descriptions-item></el-descriptions><blockquote>{{selectedCitation.quote}}</blockquote></template></el-drawer></section>
</template>
